package service;

import domain.AppUser;
import dto.*;
import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.ws.rs.NotFoundException;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

@QuarkusTest
public class AppUserServiceTest {

    @Inject
    AppUserService service;

    //Creating the subject

    private AppUserRequest createDefaultRequest() {
        return new AppUserRequest(
                "  KalleAnka  ", "Lösen123!", "KALLE@Mail.com",
                "Kalle", "Anka", LocalDate.of(1990, 1, 1),
                "Gatan 1", "Staden"
        );
    }


    @Test
    @TestTransaction
    void createUserTest() {
        AppUserRequest request = createDefaultRequest();
        AppUserResponse response = service.createUser(request);

        assertNotNull(response.id(), "Id should be generated by DB");
        assertEquals("kalleanka", response.userName());
        assertEquals("staden", response.city());
        assertNotEquals("KALLE@Mail.com", response.email());

    }

    @Test
    @TestTransaction
    void getUserByEmail() {
        AppUserRequest request = createDefaultRequest();
        service.createUser(request);
        AppUserSummaryResponse response = service.getByEmail("kalle@mail.com");
        assertEquals("kalle@mail.com", response.email());
        assertEquals("kalle", response.firstName());
    }

    @Test
    @TestTransaction
    void passwordHashTest() {
        AppUserRequest request = createDefaultRequest();
        AppUserResponse response = service.createUser(request);
        AppUser passwordHashCheck = AppUser.findById(response.id());

        assertNotEquals("Lösen123!", passwordHashCheck.password);

    }

    @Test
    @TestTransaction
    void updateUserPatch() {
        AppUserRequest request = createDefaultRequest();
        AppUserResponse response = service.createUser(request);

        AppUserUpdateRequest updateRequest = new AppUserUpdateRequest(
                null,
                null,
                "Adam",
                null,
                null,
                null,
                null
        );
        service.updateUser(response.id(), updateRequest);
        AppUser userAfterPatch = AppUser.findById(response.id());
        assertNotNull(userAfterPatch.userName);
        assertNotNull(userAfterPatch.birth);
        assertNotNull(userAfterPatch.city);
        assertNotEquals("kalle", userAfterPatch.firstName);
        assertEquals("anka", userAfterPatch.lastName);
        assertEquals("kalle@mail.com", userAfterPatch.email);
        assertEquals("adam", userAfterPatch.firstName);
    }

    @Test
    @TestTransaction
    void updatePassword() {
        AppUserRequest request = createDefaultRequest();
        AppUserResponse response = service.createUser(request);


        AppUser userBeforePatch = AppUser.findById(response.id());
        String oldPassword = userBeforePatch.password;


        service.updatePassword(response.id(), new AppUserUpdatePasswordRequest("kAka123!"));
        AppUser userAfterPatch = AppUser.findById(response.id());
        String newPassword = userAfterPatch.password;

        assertNotEquals(oldPassword, newPassword);
        assertNotEquals("kAka123!", newPassword);
        assertEquals(userAfterPatch.password, newPassword);
    }

    @Test
    @TestTransaction
    void getFail() {
        assertThrows(NotFoundException.class, () -> service.getById("not a id"));
        assertThrows(NotFoundException.class, () -> service.getByEmail("_notmail_"));

    }
}
